.TH DWG-DUMP "1" "2013-10-11" "dwg-dump - Manual"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.SH NAME
dwg-dump \- dumps data from a DWG file, into a text readable format.
.SH SYNOPSIS
.B dwg-dump 
\fIFILE \fR[\fI> outputfile.dxf\fR]
.PP
.B dwg-dump 
\fIOPTION\fR
.SH DESCRIPTION
.PP
.B dwg-dump
is a program that provides an object scanning method to see data in a 
DWG file. It is installed together with libdwg, a library to access
DWG object structures.
.PP
.B FILE
must be a DWG file, with a .dwg extension. Only versions R13 (not tested),
R14, R2000 and R2004 are accepted for now. The output goes to stdout, so it 
should be redirected to a file.
.PP
There is some more information at:
.PP
http://libdwg.sourceforge.net
.SH OPTIONS
.PP
Options are (one at time):
.PP
\fB\-h\fR, \fB\-\-help\fR      show simple usage information and exit.
.PP
\fB\-v\fR, \fB\-\-version\fR   show the program version and exit.
.SH AUTHOR
dwg-dump was written by Felipe E. F. de Castro.
.PP
e-mail: <fefcas@gmail.com>
.PP
