.TH DWG-DXF "1" "2013-10-11" "dwg-dxf - Manual"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.SH NAME
dwg-dxf \- converts a DWG file into a DXF R2000 one.
.SH SYNOPSIS
.B dwg-dxf
\fIFILE\fR
.PP
.B dwg-dxf
\fIOPTION\fR
.SH DESCRIPTION
.PP
FILE must be a DWG file, with a .dwg extension. Only versions
R13 to R2004 are accepted for now. The output goes to a file
with same basename of FILE, but with its extension being dxf.
.IP
.SH OPTIONS
.PP
Options are (one at time):
.PP
\fB\-h\fR, \fB\-\-help\fR      show simple usage information and exit.
.PP
\fB\-v\fR, \fB\-\-version\fR   show the program version and exit.
.SH AUTHOR
dwg-dxf was written by Felipe E. F. de Castro.
.PP
e-mail: <fefcas@gmail.com>
.PP
